In [ ]:
import pandas as pd
import re

from gensim.models import Word2Vec
from gensim.models import KeyedVectors
import gensim
import numpy as np

In [ ]:
data = pd.read_csv(r'C:\Users\Admin\Desktop\internship\label data\data_v2.csv')
data.head(20)

cv                                               line  tag
0    1                                   Trinh Dinh Phuc   B-I
1    1                                  Curriculum Vitae   I-I
2    1                               16 Kha Van Can Str    I-I
3    1                          Linh Dong  Thu Duc  HCMC   I-I
4    1                                     0121 658 5084   I-I
5    1                              Phuccoi996 gmail com   I-I
6    1                               DOB  March 16  1996   I-I
7    1                                         Education   B-E
8    1                                         2014 2018   I-E
9    1  Bachelor s Degree of Information Technology  D...  I-E
10   1  Telecommunications University TCU  Nha Trang  ...  I-E
11   1                                         Diagnosis   I-E
12   1                                             using   I-E
13   1                                            Lung s   I-E
14   1                                              XRay   I-E
15   1                                              with   I-E
16   1                                         Depthwise   I-E
17   1                                      Convolution    I-E
18   1             Final grade  91 100 top of the class    I-E
19   1                                        Internship   I-E

In [ ]:
def decontracted(phrase):
    # specific
    phrase = re.sub(":|-\s+|,|–\s+|-|\||\/", " ", phrase)
    phrase = re.sub(r"â€|™|“|”|;|ü|\xad|\xa0|\u200b|·|∙|�|●|�|§|•|!|▪|©|\?|\]|\[|\)|\(", "", phrase)
    phrase = re.sub(r"[^\w\s]", " ", phrase)
    
    
    phrase = re.sub(r"won\'t", "will not", phrase)
    phrase = re.sub(r"can\'t", "can not", phrase)
    
    phrase = re.sub(r"\bhcmc\b", "ho chi minh city ", phrase)
    phrase = re.sub(r"\bhcm\b", "ho chi minh ", phrase)
    phrase = re.sub(r"\bbs\b ", "bachelor of ", phrase)
    phrase = re.sub(r"r’s", "r of", phrase)
    phrase = re.sub(r"\’s", " of", phrase)
    
    # general
    phrase = re.sub(r"n\'t", " not", phrase)
    phrase = re.sub(r"\'re", " are", phrase)
    phrase = re.sub(r"\'s", " of", phrase)
    phrase = re.sub(r"\'d", " would", phrase)
    phrase = re.sub(r"\'ll", " will", phrase)
    phrase = re.sub(r"\'t", " not", phrase)
    phrase = re.sub(r"\'ve", " have", phrase)
    phrase = re.sub(r"\'m", " am", phrase)
    phrase = re.sub(r"\bim\b", "i am ", phrase)
    phrase = re.sub(r"\bi’m\b", "i am ", phrase)
    
    return phrase

In [ ]:
line = []
for i in data['line']:
    raw_clean = decontracted(str(i).lower())
    line.append(raw_clean.strip())

In [ ]:
line

['trinh dinh phuc',
 'curriculum vitae',
 '16 kha van can str',
 'linh dong  thu duc  ho chi minh city',
 '0121 658 5084',
 'phuccoi996 gmail com',
 'dob  march 16  1996',
 'education',
 '2014 2018',
 'bachelor s degree of information technology  department of computer science',
 'telecommunications university tcu  nha trang  khanh hoa  vietnam   cgpa  3 35 4 via 204 credits   thesis  pneumonia',
 'diagnosis',
 'using',
 'lung s',
 'xray',
 'with',
 'depthwise',
 'convolution',
 'final grade  91 100 top of the class',
 'internship',
 '03 2018',
 'machine learning engineer intern part time intern  cbd robotics  125 dong van',
 'cong str  district 2  ho chi minh city  vietnam',
 'work',
 'learn about and work on the technical side with focus on data analytics with using machine',
 'learning  deep learning',
 'mini projects',
 'house price prediction  amazon reviews  airline arrivals  boston marathon  author',
 'classification',
 '04 2018  7 2018',
 'data analyst intern full time intern  d

In [ ]:
from nltk import word_tokenize
from nltk.corpus import stopwords

word_lst = []
word_lst.append([''])
for j in line:
    word = word_tokenize(j)
    #filtered_words = [w for w in word if w not in stopwords.words('english')] #remove stop word
    word_lst.append(word)
word_lst

[[''],
 ['trinh', 'dinh', 'phuc'],
 ['curriculum', 'vitae'],
 ['16', 'kha', 'van', 'can', 'str'],
 ['linh', 'dong', 'thu', 'duc', 'ho', 'chi', 'minh', 'city'],
 ['0121', '658', '5084'],
 ['phuccoi996', 'gmail', 'com'],
 ['dob', 'march', '16', '1996'],
 ['education'],
 ['2014', '2018'],
 ['bachelor',
  's',
  'degree',
  'of',
  'information',
  'technology',
  'department',
  'of',
  'computer',
  'science'],
 ['telecommunications',
  'university',
  'tcu',
  'nha',
  'trang',
  'khanh',
  'hoa',
  'vietnam',
  'cgpa',
  '3',
  '35',
  '4',
  'via',
  '204',
  'credits',
  'thesis',
  'pneumonia'],
 ['diagnosis'],
 ['using'],
 ['lung', 's'],
 ['xray'],
 ['with'],
 ['depthwise'],
 ['convolution'],
 ['final', 'grade', '91', '100', 'top', 'of', 'the', 'class'],
 ['internship'],
 ['03', '2018'],
 ['machine',
  'learning',
  'engineer',
  'intern',
  'part',
  'time',
  'intern',
  'cbd',
  'robotics',
  '125',
  'dong',
  'van'],
 ['cong', 'str', 'district', '2', 'ho', 'chi', 'minh', 'city

In [ ]:
mlen = 0
for i in word_lst:
    if len(i) > mlen:
        mlen = len(i)
print(mlen)

38


In [ ]:
model = Word2Vec(window=5, min_count=1, workers=4)

In [ ]:
model.build_vocab(word_lst, progress_per=1000)

In [ ]:
len(word_lst), model.epochs, model.corpus_count

(1630, 5, 1630)

In [ ]:
model.train(word_lst, total_examples=model.corpus_count, epochs=1000)

(8249804, 9346000)

In [ ]:
model.__dict__

{'vector_size': 100,
 'workers': 4,
 'epochs': 1000,
 'train_count': 1,
 'total_train_time': 159.7372503530029,
 'batch_words': 10000,
 'sg': 0,
 'alpha': 0.025,
 'min_alpha': 0.0001,
 'window': 5,
 'shrink_windows': True,
 'random': RandomState(MT19937) at 0x20CA7BB7B40,
 'hs': 0,
 'negative': 5,
 'ns_exponent': 0.75,
 'cbow_mean': 1,
 'compute_loss': False,
 'running_training_loss': 0.0,
 'min_alpha_yet_reached': 0.00010125888733965305,
 'corpus_count': 35860,
 'corpus_total_words': 178575,
 'max_final_vocab': None,
 'max_vocab_size': None,
 'min_count': 1,
 'sample': 0.001,
 'sorted_vocab': 1,
 'null_word': 0,
 'cum_table': array([  21182472,   35772708,   49756084, ..., 2147418569, 2147451108,
        2147483647], dtype=uint32),
 'raw_vocab': defaultdict(int, {}),
 'wv': <gensim.models.keyedvectors.KeyedVectors at 0x20ca606f280>,
 'hashfxn': <function hash(obj, /)>,
 'seed': 1,
 'layer1_size': 100,
 'comment': None,
 'load': <function gensim.utils.call_on_class_only(*args, **kwargs

In [ ]:
model.wv.vector_size, model.wv.index_to_key[11], model.wv.key_to_index['university']

(100, 'chi', 16)

In [ ]:
model.wv.most_similar('university')[0:5], model.wv.most_similar('school')[0:5], model.wv.most_similar('python')[0:5]

([('degree', 0.5355433225631714),
  ('vietnam', 0.47730377316474915),
  ('secretary', 0.46717405319213867),
  ('niit', 0.4614752531051636),
  ('10', 0.4582122564315796)],
 [('regarding', 0.6963563561439514),
  ('term', 0.6576268672943115),
  ('teaching', 0.5761415958404541),
  ('province', 0.5652093291282654),
  ('level', 0.560438871383667)],
 [('java', 0.48165762424468994),
  ('qt', 0.46904000639915466),
  ('on', 0.4273933172225952),
  ('structures', 0.41176241636276245),
  ('rstudio', 0.4052179157733917)])

In [ ]:
model.save('word2vec_data_v2.bin')

In [ ]:
model = KeyedVectors.load(OUTPUT_FILE_PATH + 'word2vec.bin')

In [ ]:
with open('1_v1.txt', 'r', encoding='utf-8') as f:
    t = re.sub(':|-\s+|ü|,|\xad|\xa0|\u200b|·|∙|–\s+|\(|\)|\|�|●|�|§|•|\ufeff', ' ', str(f.read()).lower())
    text1 = t.strip().splitlines()

In [ ]:
with open('1_v2.txt', 'r', encoding='utf-8') as f:
    t = re.sub(':|-\s+|ü|,|\xad|\xa0|\u200b|·|∙|–\s+|\(|\)|\|�|●|�|§|•|\ufeff', ' ', str(f.read()).lower())
    text2 = t.strip().splitlines()

In [ ]:
def sent2idx(x):
    xidx = []
    for w in word_tokenize(x):
        if w in v:
            xidx.append(v.key_to_index[w])
    return np.array(xidx)

In [ ]:
result = []

for i in text2:
    result.append(sent2idx(i))
result

[array([1536,  597, 1344]),
 array([290, 311]),
 array([1602, 4172,  265,   99, 2078,    0]),
 array([1043,  538,  570,  389,  173]),
 array([403]),
 array([9687, 9688, 9689]),
 array([358]),
 array([8099,   36,   67]),
 array([1415,  459, 1602, 1420]),
 array([54]),
 array([9691,  177,  126,   73,  286,    2,   31,   25,  282,    2,   63,
          62]),
 array([ 543,   11, 8097, 1737, 1440, 1146,  333,   32]),
 array([3616, 8096,  415, 5689, 8095,    0]),
 array([ 334, 4247, 3087,   33, 3633,  126,   73, 4214,    8, 4221, 3471,
           0]),
 array([ 950,  668, 8091,  650,    2,    4,  421,    0]),
 array([244]),
 array([3094,  155,   59,   85,  341,  373,  107,  341, 8088, 1218, 5687,
         538,  265]),
 array([ 926, 2078,    0,   98,   74,   34,   41,   26,   35,   32]),
 array([  16,  142,   61,    1,   16,   15,    4,   87, 1340,    8, 1439,
          15,   18,  714,    8,   33,  155]),
 array([ 59, 300,  59,   0]),
 array([8103, 1081, 1341, 1357, 1229, 2641, 8105, 8120, 811

In [ ]:
maxlen = 0
for j in result:
    if len(result) > maxlen:
        maxlen = len(result)
maxlen

107

In [ ]:
Xtrain_idx = []
maxlen = 0
for x in text1:
    Xtrain_idx.append(sent2idx(x))
    if len(Xtrain_idx[-1]) > maxlen:
        maxlen = len(Xtrain_idx[-1])
maxlen

42

In [ ]:
for i, x in enumerate(result):
    if len(x) < maxlen:
        result[i] = np.hstack((x, np.zeros(100-len(x))))
result = np.array(result)

In [ ]:
result[0]

array([1536.,  597., 1344.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.])

In [ ]:
word_vectors = model
word_vectors.save("word2vec.bin")

In [ ]:
import gensim.models.keyedvectors as word2vec
model = word2vec.KeyedVectors.load_word2vec_format('GoogleNews-vectors-negative300.bin', binary=True)

In [ ]:
model.__dict__

{'vector_size': 300,
 'index_to_key': ['</s>',
  'in',
  'for',
  'that',
  'is',
  'on',
  '##',
  'The',
  'with',
  'said',
  'was',
  'the',
  'at',
  'not',
  'as',
  'it',
  'be',
  'from',
  'by',
  'are',
  'I',
  'have',
  'he',
  'will',
  'has',
  '####',
  'his',
  'an',
  'this',
  'or',
  'their',
  'who',
  'they',
  'but',
  '$',
  'had',
  'year',
  'were',
  'we',
  'more',
  '###',
  'up',
  'been',
  'you',
  'its',
  'one',
  'about',
  'would',
  'which',
  'out',
  'can',
  'It',
  'all',
  'also',
  'two',
  'after',
  'first',
  'He',
  'do',
  'time',
  'than',
  'when',
  'We',
  'over',
  'last',
  'new',
  'other',
  'her',
  'people',
  'into',
  'In',
  'our',
  'there',
  'A',
  'she',
  'could',
  'just',
  'years',
  'some',
  'U.S.',
  'three',
  'million',
  'them',
  'what',
  'But',
  'so',
  'no',
  'like',
  'if',
  'only',
  'percent',
  'get',
  'did',
  'him',
  'game',
  'back',
  'because',
  'now',
  '#.#',
  'before',
  'company',
  'any',

In [ ]:
model.vector_size, model.index_to_key[1810], model.key_to_index['university']

(300, 'university', 1810)

In [ ]:
model.most_similar('university')

AttributeError: 'Word2Vec' object has no attribute 'most_similar'

In [ ]:
import re

s = 'i n t e r n   a s   f r o n t  e n d   a t   t m a s o l u t i o n s      1 1   0 2   2 0 1 8 ,0 2   0 2   2 0 1 9 s e m i n a r   o f   d o i n g   r e s e a r c h   o n a u g m e n t e d   r e a l i t y    a r thai'
raw = re.sub('(\w{1})\s+(\w{1})\s{1}', r'\1\2', s)
raw

'intern  as  frontend  at  tmasolutions     11  02  2018,02  02  2019seminarofdoing  research  onaugmentedreality   arthai'